Makefile
formats/mlab-site-info.json.jsonnet
formats/raw-sites.json.jsonnet
sites.jsonnet
sites/_default.jsonnet
sites/lga0t.jsonnet
sites/tyo01.jsonnet

This change is the first commit that illustrates how we could move the m-lab/operator/plsync sites.py and slices.py configuration to a more flexible, complete, and representative form using JSONNET.
The two examples are lga0t (a test site) and tyo01 (a synthetic site run from a GCE VM). And, the first format generates the same format as the current mlab-site-info.json files used by mlab-ns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/1)

Add initial example and template for siteinfo and formats

---

.gitmodules
Makefile
experiments.jsonnet
formats/mlab-host-ips.json.jsonnet
lib/site.jsonnet
lib/site_test.jsonnet
sites.jsonnet
sites/_default.jsonnet

This change adds three new components:
* lib/site.jsonnet - a library for generating network specs for machines, experiments at a given site.
* mlab-host-ips.json.jsonnet - an output format matching the current mlab-host-ips.json format.
* experiments.jsonnet - a basic declaration of current M-Lab experiments.
With these three components, we can generate both mlab-site-info.json and mlab-host-ips.json formats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/2)

Add library for site network specs and add mlab-host-ips.json format

---

lib/site.jsonnet
lib/site_test.jsonnet

Complementary to https://github.com/m-lab/index2ip/pull/14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/7)

Use base10 suffix for IPv6 addresses

---

Dockerfile
Makefile
cloudbuild.yaml
formats/measurement-lab.org.zone.jsonnet
formats/sites.json.jsonnet

This change adds new support for deploying generated siteinfo configs to a GCS bucket using CloudBuild. As well, this change is a precursor to supporting the siteinfo API using a cloud "loadbalancer with GCS bucket backend".
In service of that API, this change creates the following target directories:
* `/v1/sites/` - experiment, node, and site metadata
* `/v1/zones/` - generated DNS zone files & diffs.
* `/configs/`  - archived versions of the above
For example, once the load balancer is configured, the ultimate API resources will look like:
* https://siteinfo.mlab-sandbox.measurementlab.net/v1/sites/locations.json
* https://siteinfo.mlab-sandbox.measurementlab.net/v1/sites/hostnames.json
* https://siteinfo.mlab-sandbox.measurementlab.net/v1/sites/sites.json
* …

Add automated generation for siteinfo API and CloudBuild deployment

---

Makefile
zonediff.sh

This change adds basic support for generating the measurement-lab.org.zone diff for the current configs relative to the version currently published in the siteinfo api.
There is one limitation of this approach: it is not guaranteed that the version currently read from siteinfo API is actually the version deployed to dns.measurementlab.net -- to guarantee the diff we would want to source the current zone from dns.measurementlab.net or perhaps only source the version at mlab-oti.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/10)

Add basic support for generating the zone diff

---

experiments.jsonnet

This change adds the rsync modules to preserve the ability to generate some configs for rsync during the platform migration to k8s. Once that migration is complete we can eliminate the rsync module fields (which have no meaning on the new platform).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/15)

Add rsync modules to experiments.jsonnet

---

formats/sites/locations.json.jsonnet

This change adds the `uplink_speed` key to the siteinfo locations.json format.
Part of https://github.com/m-lab/dev-tracker/issues/365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/18)

Add uplink_speed to site locations

---

experiments.jsonnet

This PR adds back the OONI experiment to `experiments.json`.
Migrating the DNS configuration to siteinfo had the unintended side effect of removing the DNS entry for this experiment. Chatting with the OONI folks, I've discovered they might still be using it somewhere. Also, it's making scraper fail on the legacy platform since it tries to rsync `mlab.ooni.<node>.<site>.measurement-lab.org`. This PR + redeploying DNS zones should fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/24)

Add OONI experiment back

---

formats/zones/measurement-lab.org.zone.jsonnet
lib/site.jsonnet

This PR adds a DNS record for `r1.<site>`, which is needed by the `configure_drac.py` script to find what's the default gateway to set on a DRAC.
Here's the diff generated by this change (at least until it's overwritten by another build):
https://siteinfo.mlab-sandbox.measurementlab.net/v1/zones/measurement-lab.org.zone.diff
Closes https://github.com/m-lab/siteinfo/issues/28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/29)

Add DNS record for the router (r1.<site>)

---

sites/mnl01.jsonnet

This PR updates the switch details for MNL01. This site's upstream has been recently upgraded to 10g and the switch is a Juniper now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/31)

Update uplink and switch make for MNL01

---

formats/zones/measurement-lab.org.zone.jsonnet
lib/site.jsonnet

This removes the `r1.<site>` DNS entry generation since the only use case for it has already been handled differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/32)

Revert "Add DNS record for the router (r1.<site>)."

---

cmd/mlabconfig.py

Since we still rely on mlabconfig.py for a lot of current, non-legacy things, we decided to move it out of the legacy m-lab/operator repository. The script is being placed a `cmd/` subdirectory in anticipation that it will eventually be rewritten in Go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/33)

Moves mlabconfig.py from the m-lab/operator repo to this one.

---

cmd/mlabconfig.py

This PR adds `d` as a possible decoration in mlabconfig.py. This allows to leverage the existing code to generate targets where `hostname` is `<node>d.<site>.measurement-lab.org`.
The rationale behind it is that then we can call `mlabconfig.py` with a `--template` such as `https://<user>:<pass>@reboot.<project>.measurementlab.net/v1/e2e?target={{hostname}}` with the decorated `hostname` to generate a target for each BMC on the M-Lab infrastructure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/34)

Add 'd' as decoration to support BMCs

---

formats/adhoc/sitegeo.json.jsonnet
sites/chs0c.jsonnet
sites/iad0c.jsonnet
sites/lax0c.jsonnet
sites/oma0c.jsonnet
sites/pdx0c.jsonnet
sites/tyo01.jsonnet
sites/tyo02.jsonnet
sites/tyo03.jsonnet

This change adds a new output format for site GeoJSON to feed into a new "site location" map.
The format is placed in v1/adhoc for now while we experiment with the format. If the format is useful, we should move it to `v1/sites/geo.json`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/36)

Add initial sitegeo output

---

formats/zones/measurement-lab.org.zone.jsonnet

Some blackbox exporter monitoring targets use the flat-decorated hostnames and require that we include these in the DNS zone. This change adds them back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/40)

Add decorated flat hostnames when specified

---

formats/adhoc/upgrade.json.jsonnet

We have a few sites and machines that are already migrated to k8s, and thus should be added upgrade.json. This PR adds a local variable that lists these sites, and specifies which machine have already been migrated.
NOTE: The sort order of the output may has changed somewhat. The sort will now be by node, then by site, which will group mlab1s, mlab2s, etc. (i.e., nodes at a site will not appear next to one another in the list).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/47)

Adds already-migrated sites and machines to upgrade.json.

---

cors-settings.json
cors-settings.json.template
create_siteinfo_api.sh

This PR adds the CORS configuration via `gsutil` to `create_siteinfo_api.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/52)

Apply CORS settings to the siteinfo bucket

---

sites/arn06.jsonnet
sites/fra05.jsonnet

This PR adds the IPv6 addresses for ARN06 and FRA05.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/54)

Add IPv6 addresses for ARN06 and FRA05

---

experiments.jsonnet

Neubot would like to use the `*.measurement-lab.org` wildcard certificate too, so it will need "flattened", in addition to NDT.

Creates 'flattened' hostnames for neubot.

---

sites/_default.jsonnet
sites/bcn01.jsonnet

RSTP = Rapid Spanning Tree Protocol. The default value will be 'yes'. It will be disabled for BCN01.
This is necessary because we have one site, BCN01, which needs to have RSTP disabled. From the site host:
> That port is connected to switch in the DMZ at CATNIX.  In all IXP's, the customer are not allowed to be visible as L2 bridges. This means that they should not speak STP (spanning tree) or any other (proprietary) L2 specific protocol.
>
> Could you disable STP in that interface?
Adding this new setting to the default site template allows us to not have to exception handle for this setting. `genconfig.py` in the switch-config repo will need to take this new setting into account, which will be a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Adds a new configuration to the default site config for 'rstp' 

---

sites/atl03.jsonnet
sites/dfw02.jsonnet
sites/iad03.jsonnet
sites/lax02.jsonnet
sites/lga03.jsonnet
sites/mia03.jsonnet
sites/nuq04.jsonnet
sites/ord03.jsonnet

Well, all but SEA02, which was already correct. These circuits were upgraded a year ago, but never update in our docs, apparently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/64)

Updates all U.S. Tata sites to 10g

---

formats/sites/sites.json.jsonnet

This PR adds a DRAC entry under each node in `sites.json`. It's also the first step to add the DRAC configuration to stage1 ISOs.
Closes https://github.com/m-lab/siteinfo/issues/67.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/68)

Add DRAC entries to sites.json

---

cmd/mlabconfig.py
formats/sites/sites.json.jsonnet

This PR changes `export_mlab_server_network_config` to also read the DRAC's IPv4 address from `sites.json`. This is needed so that `drac_ipv4_address` can be replaced in an epoxy-images configuration template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/70)

Read DRAC's IPv4 from siteinfo

---

formats/adhoc/upgrade-2nd.json.jsonnet
formats/adhoc/upgrade-3rd.json.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/72)

Adds missing site ARN06 to the list sites that are already fully migrated to ePoxy/k8s

---

formats/zones/measurement-lab.org.zone.jsonnet

... and sets origin A records to the same as measurementlab.net.
Currently, the MX records for the measurement-lab.org zone point to a PlanetLab address, which is no longer accurate or correct. Indeed, the domain measurement-lab.org does not handle either incoming or outgoing email at all, so this PR just dispenses with the MX records altogether. There is no need to advertise a mail exchange for a domain which handles no email.
Also, the existing A record for the origin points to some IP belonging to PlanetLab. This PR changes the origin A record(s) to point to the same IPs as our measurementlab.net domain. @critzo, **if this PR is accepted** and merged, would you be able to configure Firebase to redirect any request for measurement-lab.org to measurementlab.net, just like we already do …

Removes MX records for measurement-lab.org 

---

formats/zones/measurement-lab.org.zone.jsonnet

In order for Google Firebase to be able to handle the measurement-lab.org domain, we have to verify the domain with a TXT record. Not ideal, but I wasn't offered another way to verify the domain and this is just a one-time thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/75)

Adds TXT for Google site verification for Google Firebase

---

formats/zones/measurement-lab.org.zone.jsonnet

@nkinkade the naked domain now redirects as expected, but we need these additions to also redirect the www sub-domain. Similar to the measurementlab.org domain: https://raw.githubusercontent.com/m-lab/dns-zones/master/measurementlab.org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/77)

added www subdomain so it redirects as well

---

Dockerfile

Builds have started failing with:
```
Step #1: Error relocating /usr/bin/jsonnet: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```
I think there has been a incompatible ABI change between `alpine:latest` (the version we use to build) and `alpine:3.9`. Using a tagged version of Alpine for both building and running seems the safest option to me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/86)

Use alpine:3.9 to build the CPP version of jsonnet

---

sites/ams08.jsonnet
sites/arn03.jsonnet
sites/mad02.jsonnet
sites/par02.jsonnet
sites/prg02.jsonnet

This PR updates the `uplink` field on siteinfo for the five Level3 sites that were upgraded this morning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/85)

Update Level3 sites to 10g

---

sites/del02.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/87)

Removes the IPv6 prefix for DEL02, since they were unable to provide us with a /64

---

formats/zones/measurement-lab.org.zone.jsonnet

This new nameserver is also configured as the "primary" nameserver in the SOA record.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/93)

Adds new NS record ns.measurementlab.net 

---

formats/sites/switches.json.jsonnet

This PR adds a new `ipv4_prefix` field to `switches.json`. `switches.json` is used by `genconfig.py` (in the https://github.com/m-lab/switch-config repo) to generate the switch configuration. 
Even if `genconfig.py` has started using siteinfo, the ipv4 prefix must  still be specified via a command line flag. 
This change will allow removing that flag from genconfig.py, removing a potential source of human error and also making it possible for that script to generate *all* the switch configurations in a single run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/98)

Add ipv4_prefix to switches.json

---

formats/zones/measurement-lab.org.zone.jsonnet

The new configuration with ns.measurementlab.net seems to be working just fine, so we can now safely remove the ISC nameserver from the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/99)

Removes NS record for sns-pb.isc.org.

---

formats/zones/measurement-lab.org.zone.jsonnet

This change is being made after a discussion in the most recent Platform Development meeting concluded that a TTL of 5m may be too small and that 24h may be too large. A 1h TTL was seen to be  middle-of-the-road compromise. Part of the hope of this is to see if this change might budge (lower) some of the persistent OneBox error rates, as some of them may be related to DNS failures that are the result of our current less-than-ideal DNS configuration (1 VM in the US and 1 VM in Western Europe). This may also be alleviated by us moving to Cloud DNS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/107)

Increases the default zone TTL from 5m to 60m.

---

sites/mad05.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/110)

Fixes a typo in the IPv6 prefix for mad05.

---

formats/sites/annotations.json.jsonnet
sites/_default.jsonnet

This change adds a new format to siteinfo that outputs the schema used by the `annotator.ServerAnnotations` type from uuid-annotator. This information would be loaded at start time by the uuid-annotator from the siteinfo API and used to populate the M-Lab Server fields in the uuid archives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/113)

Add server annotation format for uuid-annotator

---

formats/sites/annotations.json.jsonnet

This change expands the definition of the annotations format to include the site netblock for use by the uuid-annotator to accept that a given "server" annotation is for an IP address in the site netblock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/117)

Add network information for server annotation

---

formats/v1/sites/hostnames.json.jsonnet
formats/v1/sites/sites.json.jsonnet
formats/v1/zones/measurement-lab.org.zone.jsonnet
lib/site.jsonnet
sites/_default.jsonnet
sites/lga0t.jsonnet
sites/lga1t.jsonnet

This PR allows us to configure project on a per node basis. This could be the basis upon which we start to migrate many mlab4 to production. This does not change current v1 output, other than to change the `machines` field of a site and to add a new `project` field to each machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/119)

Allow configuring project on a per-node basis.

---

lib/site.jsonnet

But only if the version being built is v2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/120)

Configures lib/site.jsonnet to output project-subdomain domain names

---

formats/v1/zones/measurement-lab.org.zone.jsonnet
formats/v2/zones/measurement-lab.org.zone.jsonnet

Fixes a type I made across all Cloud DNS nameservers. They should all be prefixed with `ns-`, not `ns1-`. Not sure how I got that "1" in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/127)

Fixes Cloud DNS nameserver names. They should all start with 'ns-' not 'ns1-'

---

cmd/mlabconfig.py

Passes the value of the `--project` flag to all functions that also want the value of the `--select` flag, where selecting on node project makes sense. These changes should be a no-op for existing users of mlabconfig.py, until those users are upgraded to take advantage of it.
This represents one small change toward moving away from the old "all mlab4s are staging" paradigm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/128)

Adds a new --project flag for selecting nodes.

---

Dockerfile.python
cloudbuild.yaml
cmd/mlabconfig_test.py

This PR cherry-picks (not in the git sense, but in the `cp` sense) the latest version of [mlabconfig.py unit tests from the old operator repository](https://github.com/m-lab/operator/blob/master/plsync/mlabconfig_test.py), and makes any changes necessary to the file for it to work today. I decided to, for now, avoid trying to convert the file to use python3, though this should in theory be pretty easy with `2to3` or similar. I also added one unit test to be sure that selecting on a GCP project that does not exist in the sample sites data yields no Prometheus targets.
For the sake of transparency about what changed (not very much), this is the full diff:
```
--- plsync/mlabconfig_test.py	2019-06-11 14:21:45.512181155 -0500
+++ ../siteinfo/cmd/mlabconfig_test.py	2020-03-12 …
```

Brings back unit tests to mlabconfig.py, albeit with python 2.7 :/

---

formats/v1/zones/measurement-lab.org.zone.jsonnet

We would like to start using LetsEncrypt wildcard certificates for experiments. Doing this requires DNS01 ACME challenges, which cert-manager handles from the platform clusters. However, the Cloud DNS zone for measurement-lab.org is not yet public. This PR delegates the `_acme-challenge` subdomain to the production Cloud DNS servers, which are the ones that cert-manager can and does update with appropriate challenge TXT records. This PR only applies this delegation to our current v1 zone, not to any Cloud DNS instance. This _should_ start allowing ACME challenges to start working for measurement-lab.org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/133)

Delegates ACME DNS01 challenge records to Cloud DNS

---

lib/site.jsonnet
lib/site_test.jsonnet

Previous changes to this repo already created flat experiment names by default for v2 outputs. However, switch names, machine names and drac names were left in dotted format. This PR fixes that so that hopefully **all** names are flat in v2 now. This make the possibility that the wildcard TLS LetsEncrypt certificates we already generate in the cluster could possibly be used for swtiches, DRACs or machines in some way, and if not then at least we are being consistent about flattening all host parts of domain names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/132)

Flattens machine names and drac name, too.

---

README.md
deploy_dns.sh
formats/v1/zones/measurement-lab.org.zone.jsonnet

This PR configures the appropriate CNAME records in each zone to be able to support having cert-manager use a dedicated  zone for ACME challenges so that it doesn't have full write permissions to our primary zones files.
Since our zones get overwritten every deployment, this PR also includes changes to `deploy_dns.sh` to preserve the `acme` subdomain delegation to the new dedicate zones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/135)

Configures CNAME records for ACME challenges

---

deploy_dns.sh
experiments.jsonnet

This change adds a short name for "ndt" and "neubot" and provides a migration path for mlab-ns and other legacy users of the "iupui" or "mlab" parts of ndt and neubot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/137)

Add short names for ndt and neubot

---

cmd/mlabconfig.py

prometheus-support builds are failing with:
```
+python3 ./[secure]config.py --format=prom-targets --sites https://siteinfo.[secure]-sandbox.measurementlab.net/v2/sites/sites.json '--template_target={{hostname}}:443' --label service=ndt7 --label module=tcp_v4_online --project [secure]-sandbox --select ndt.iupui
Traceback (most recent call last):
File "./[secure]config.py", line 501, in <module>
main()
File "./[secure]config.py", line 460, in main
sites = json.loads(urllib.request.urlopen(options.sites).read())
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
This PR passes the data returned by urllib through `.decode('utf-8')`. I do not get this error on my local machine, even without …

Adds .decode('utf-8') when reading json-decoding the data returned by urllib

---

deploy_dns.sh
formats/v1/zones/measurement-lab.org.zone.jsonnet
formats/v2/zones/measurement-lab.org.zone.jsonnet
lib/site.jsonnet

This PR fixes issue #134 in which switch records were not included in the base v2 measurement-lab.org domain.
Additionally, since switches are sort of a special case, not (currently) belonging to any particular project, this PR adds v2 switch names (e.g., s1-den04) to the v1 zones to ease the transition from v1 to v2 naming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/141)

Fixes issue #134 + adds v2 switch names to v1 zones

---

sites/_default.jsonnet
sites/hkg01.jsonnet
sites/hkg02.jsonnet
sites/hnd01.jsonnet

We keep track of switch models in siteinfo, and should also keep track of machine model. This will become increasingly important as we get more sites running R640s and the machine models on the platform become not alike.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/143)

Adds machine model to default site template, and to any site files needing it.

---

cloudbuild.yaml
deploy_dns.sh

We never did use the v1 measurement-lab.org zone in Cloud DNS. This PR deploys the v2 zone to the production instance in Cloud DNS. Once this is done, the next step will be to change the glue records for the domain with the registrar to complete the migration to Cloud DNS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/147)

Deployes the v2 measurement-lab.org zone to Cloud DNS instead of the v1 zone.

---

formats/v2/zones/measurement-lab.org.zone.jsonnet

This record is in the old zone, and I had failed to add it to the v2 zone for measurement-lab.org. We probably don't even need the `.*.measurement-lab.org` domain in the certificate any longer, but  to be safe there is no harm in including for the foreseeable future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/149)

Adds missing _acme-challenge CNAME for DNS01 validation

---

sites/bog05.jsonnet
sites/gig02.jsonnet

The same IPv4 prefixes were specified for multiple sites. BOG05 was given the same prefix as for LHR07, and GIG02 was given the same prefix as for MIL06. ThIs PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/155)

Fixes IPv4 prefixes for GIG02 and BOG05

---

sites/mnl02.jsonnet

The default value is R630, so unless we override the field it'll be wrong for most new sites.
I think there are other recent sites where didn't set this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/159)

Add machines override for mnl02

---

sites/lba01.jsonnet
sites/lga0t.jsonnet
sites/lga1t.jsonnet

PR #181 broke or mis-specified a few site jsonnet files. For example, `machines+` was defined twice for the lga0t and lga1t sites, causing them to look like production sites (e.g., mlab1-lga0t.mlab-oti.measurement-lab.org).  The changes in PR #181 were largely generated by a shell script. I'm not sure what went wrong, but this should resolve the few files that got broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/182)

Fixes a few malformed/malspecified jsonnet site files

---

sites/tnr01.jsonnet

In PR #183 I forgot/failed to remove the config for the old 1g uplink that set auto-negotiation of the link to false. This PR resolves that small issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/184)

Enables auto-negotiation on uplink port for TNR01

---

cloudbuild.yaml

This was an oversight from PR #185. I didn't previously realize that `cbif` required this env variable, but it makes sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/186)

Sets a global PROJECT_ID var for cbif

---

cloudbuild.yaml

This PR sets the env variable SINGLE_COMMAND=true for all remote build trigger steps. If this isn't set, `cbif` will apparently attempt to run each arg as a separate command. The [documentation for the flag](https://github.com/m-lab/gcp-config/blob/master/cmd/cbif/main.go#L51) seems misleading to me, but I may be reading it wrong:
> Run each argument as an individual command.
I read that to mean that to mean the opposite of what the flag apparently does??
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/187)

Sets SINGLE_COMMAND=true for all siteinfo-cbif steps

---

README.md
cloudbuild.yaml

This PR introduces the use of a secret from the GCP Secret Manager into the Cloud Build for this repo. This allows `cbctl trigger` to use an authenticated Github client when triggering builds for private repositories, which is currently only the switch-config repo. Instructions on how to create the secret in Secret Manager is included in the README.md update in this PR.
NOTE: The build step for triggering a build in the switch-config repository is necessarily ugly. For some reason the [officially documented and supported way](https://cloud.google.com/build/docs/securing-builds/use-secrets) to use secrets from the Secret Manager in the build _requires_ you to use an `entrypoint` of /bin/bash (or at least some shell?). This seems very hackish, and it's unclear to me why this would be …

Uses Github token from Secret Manager

---

README.md

The current documentation, if followed, will cause a newline to be appended to the secret in Secret Manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/190)

Adds -n flag to echo in documentation for adding secrets to Secret Manager

---

cloudbuild.yaml

Currently, adding ePoxy Host Datastore entities is a manual process. Not only is it a manual process, but an operator has to _remember_ to do it. If it is not done, nodes at a new site cannot boot, and this can sometimes cause delays new site deployments, especially if an operator is not available to help the install technician during the install. This PR adds a new build step to automate this process, leveraging the [new `sync` operation of the epoxy_admin tool](https://github.com/m-lab/epoxy/pull/101).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/191)

Adds build step to sync ePoxy Datastore entities to sites in this repo

---

sites/bog05.jsonnet

When this site was first being deployed, there was confusion about both the IPv4 and IPv6 prefixes. Somehow, the IPv6 prefix for this site never got entered.  This PR resolves that oversight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/196)

Adds missing IPv6 prefix to bog05

---

cmd/mlabconfig.py
cmd/mlabconfig_test.py

A very small handful of sites (3) do not support IPv6. We still need to scrape these targets with IPv6 so that we have an explicit IPv6 failure metric for the Locate Service. However, we also need alerting for when IPv6 at a site/machine has been down for too long. This new `ipv6` label will allow us to filter sites/machine that don't have IPv6 configurations from the list of sites/machines where IPv6 is legitimately down.  The two values possible values are:
* `ipv6="present"`
* `ipv6="missing"`
This PR is related to PR https://github.com/m-lab/prometheus-support/pull/836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/197)

Adds new 'ipv6' label to BBE experiment scrape targets

---

sites/yyz05.jsonnet

YYZ05 was provisioned using the older hardware from YYZ02, which were
R630s. YYZ02 was the CIRA-hosted 1g HE site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/202)

Changes YYZ05 machine types to R630

---

retired.jsonnet
sites.jsonnet
sites/yyz02.jsonnet

YYZ02 equipment (old CIRA 1g HE site) was used to provision a new 10g Telia site YYZ05.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/203)

Retires site YYZ02

---

cloudbuild.yaml

The stage 3 image is the same for every node, and does not need to be rebuilt on every change to this repository. This _should_ mean that the stage3 image will only get built a single time, when the epoxy-images repository is tagged, creating a new image version. I believe this change will make it safe to include package upgrades in the stage3 build and have a controlled deployment of the updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/214)

Remove build trigger for epoxy-images-stage3

---

deploy_dns.sh
sites.jsonnet
sites/chs0t.jsonnet
sites/pdx0t.jsonnet

CHS0T is located in Moncks Corner, SC
PDX0T is located in Dalles, OR
I had to make a change to the DNS deployment script to allow builds for this repo to work with NDT cloud sites. There was previously a very loose check to be sure that every experiment had the same number or DNS resource records, to check for any massive and obvious failure in the generation of the zone file. However, that check would fail with NDT cloud nodes, because resource records are only added for NDT, not other experiments, causing the RR counts to be different for each experiment, causing the build to fail. This PR just removes that check, since it was of questionable utility to being with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Adds new cloud NDT sites chs0t and pdx0t

---

sites/chs0t.jsonnet
sites/pdx0t.jsonnet

We are going to start our more conservative for virtual/cloud nodes/sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/220)

Configures virtual sites pdx0t/chs01 as 1g

---

formats/v2/sites/max-rates.json.jsonnet
formats/v2/sites/uplinks.json.jsonnet

The format will ultimately be used to populate the value of the ndt-server flag `-txcontroller.max-rate`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/221)

Adds new "max-rates" v2 format

---

sites.jsonnet
sites/_default.jsonnet
sites/bru06.jsonnet
sites/cgk01.jsonnet
sites/chs0t.jsonnet
sites/fra07.jsonnet
sites/iad07.jsonnet
sites/lax07.jsonnet
sites/lax0t.jsonnet
sites/lhr09.jsonnet
sites/ord07.jsonnet
sites/pdx0t.jsonnet
sites/sea09.jsonnet
sites/sin02.jsonnet
sites/tpe02.jsonnet

This PR adds 11 new production (mlab-oti) GCE virtual sites, as specified in the "[Fast Canary](https://docs.google.com/document/d/1O2XGMZu7lEQ0wC8WVd0HnC8MZFLQatv2TbnX5YCrc1c/edit#heading=h.99veqx62rc8w)" section of the "To the cloud" document.
Except for CGK01 (Jakarta), all site files are copies of existing sites in their respective metros, meaning that all of the location data should be equal to whatever we already use for that metro. 
Three of these new virtual sites are IPv6 enabled: LAX07, LHR09, TPE02.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/224)

Adds 10 new production GCE virtual sites

---

formats/v2/sites/annotations.json.jsonnet

The uuid-annotator uses the field Annotations.Machine to specify _only_
the machine (e.g., mlab1, mlab3, etc.) not the FQDN of the host. This
commit makes the field Name reflect the FQDN, and Annotations.Machine to
be only the machine at the site to be consitent with how the
uuid-annotator understands these terms/fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/233)

Uses FQDN for Name field in v2 annotations.json

---

retired.jsonnet
sites.jsonnet
sites/syd02.jsonnet

SYD02 was somehow replaced by SYD05. The details are fuzzy:
https://github.com/m-lab/ops-tracker/issues/1563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/236)

Retires Vocus site SYD02

---

sites/oma01.jsonnet

The machine name should have been mlab4, not mlab1, and the network config should be static, not extending the default template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/244)

Fixes the machine and network config for virtual site oma01

---

sites/chs0t.jsonnet
sites/iad08.jsonnet

This PR adds a second VM (mlab2) to testing site chs0t and a second VM (mlab3) to virtual staging site iad08. Interestingly, we've never had a non-mlab4 machine in the staging cluster, but we do now.
This PR tests having multiple VMs at a virtual site in preparation for adding two new VMs to the virtual site bom03. The goal is to test how virtual sites compare to physical sites in a metro when they have the same number of nodes and the same probability of being selected.
```
$ kubectl --context mlab-sandbox get nodes | grep chs0t
mlab1-chs0t.mlab-sandbox.measurement-lab.org   Ready    <none>                 226d   v1.22.15
mlab2-chs0t.mlab-sandbox.measurement-lab.org   Ready    <none>                 23h    v1.22.15
$ kubectl --context mlab-staging get nodes | grep iad08 …
```

Tests virtual sites with multiple VMs

---

retired.jsonnet
sites.jsonnet
sites/_default_virtual.jsonnet
sites/oma01.jsonnet
sites/ord07.jsonnet
sites/pdx01.jsonnet
sites/sea09.jsonnet

This PR resolves the issue a couple of virtual sites not being properly geolocated with respect to the GCP region they were deployed in. The improper geolocation was intentional, but was part of the early "fast canary" for virtual sites. Now that we have passed that phase, we want sites more accurately geolocated.
pdx01 is replacing sea09 for GCP region us-west1, which is actually in Oregon and closer to Portland than Seattle. sea09 is being retired.
mlab1-oma01 is replacing ord07 for GCP region us-central1, being added to existing virtual site oma01 (mlab4-oma01 in staging already existed). ord07 is being retired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/249)

Adds virtual site pdx01, and virtual node mlab1-oma01

---

sites.jsonnet
sites/tlv01.jsonnet

In the past week or so Google opened a new GCP region,  `me-west1`, in Tel Aviv, Israel. This PR adds a virtual site, TLV01, in this new region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/252)

Adds new GCP virtual site TLV01

---

retired.jsonnet
sites.jsonnet
sites/yqm01.jsonnet

All of the other 1g CIRA-managed HE sites went down a month or two ago when the CIRA contracts expired. For some reason this site never went down, but according to CIRA the contract is expired. This seems like a possible oversight within HE. In any case there is new Google-managed 10g HE site on the way, which will be replacing this one soon. This commit is retiring the legacy 1g site before HE abruptly disconnects it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/254)

Retires 1g CIRA-managed HE site YQM01

---

sites/bom03.jsonnet

This is in anticipation of likely testing bom03 as a virtual-only metro.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/255)

Adds a 3rd VM (mlab3) to virtual site bom03

---

cloudbuild.yaml

This Cloud Build config was still using the "latest" version of the various cbif images, which are no longer getting updates. 1.0 is the latest tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/257)

Uses v1.0 of siteinfo-cbif and gcloud-jsonnet-cbif

---

sites/chs0t.jsonnet
sites/lax0t.jsonnet
sites/pdx0t.jsonnet

Also removes IPv6 addresses from all machines that had them. Static IPv6 configs for virtual machines are not workable until GCP supports creating static IPv6 addressing.
Also updates the machine type for a couple of VMs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/258)

Updates IPv4 address for mlab1-chs0t

---

sites/gru05.jsonnet
sites/hnd06.jsonnet

We are going to expand the experiment of migrating entire metros from physical infrastructure to virtual to Sao Paulo (gru) and Tokyo (hnd). This PR adds two additional VMs to the existing virtual sites in these metros.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/259)

Adds mlab2 and 3 to virtual sites gru05 and hnd06

---

sites/fra07.jsonnet
sites/waw01.jsonnet

This change adds one additional cloud VM to two cloud sites in preparation for directing some traffic from PRG to regional cloud sites.
Part of:
* https://github.com/m-lab/ops-tracker/issues/1720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/261)

Add mlab2 to waw01 and fra07

---

sites/chs0t.jsonnet

The load balancer IP for mlab1-chs0t was incorrect, probably because of my Terraform testing and redeployment.
chs0t actually didn't have an mlab2 machine, though our siteinfo configs said it did, so I just updated the existing machine record with the IP address of the new mlab2 machine. This mlab2 machine is not part of a MIG, but is out older, standard type of VM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/265)

Updates IPv4 info for virtual site chs0t

---

sites/chs01.jsonnet
sites/iad07.jsonnet
sites/yul07.jsonnet

This is a test to see whether in some cases standard networking actually performs better thatn premium network in GCP. These are all mlab2 machines at existing sites where the mlab1 VM is premium network tier. We will be able to compare results between the two VMs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/266)

Adds 3 new VMs with network-tier of STANDARD

---

sites/chs0t.jsonnet
sites/iad08.jsonnet
sites/lax08.jsonnet
sites/lax0t.jsonnet
sites/oma01.jsonnet
sites/pdx0t.jsonnet

In sandbox, somehow the IPv4 addresses we had configured for the loadbalancer were all wrong, and (just coincidentally?) the wrong IP addresses happened to be assigned to VMs in the managed instance group such that things still worked, even though the loadbalancer was being bypassed. This seems like a huge coincidence, and may have been user error on my part at some point in the past.
Additionally, after I brought the staging VMs under Terraform control their ephemeral IPv6 addresses changed, and this commit updates them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/270)

Fixes IP addresses for virtual machines

---

retired.jsonnet
sites.jsonnet
sites/lax05.jsonnet

This is part of the retirement of roughly 1/3 of physical sites to reduce costs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/273)

Retires Zayo site LAX05

---

retired.jsonnet
sites.jsonnet
sites/nuq02.jsonnet

The rebooted ISC site will be a test case for a 1U, single server site: https://github.com/m-lab/ops-tracker/issues/1795
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/275)

Retires ISC site nuq02

---

sites/oma01.jsonnet

The static IPv6 address was named like the following (capitalization mine for emphasis). This is probably okay, except for the fact that we need to run a script that counts on a correct name:
mlab4-oma01-mlab-staging-meaSRUment-lab-org-v6
Deleting and recreating the static address with a correct name changed the address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/280)

Updates IPv6 address for mlab4-oma01

---

sites/ams10.jsonnet
sites/bru06.jsonnet
sites/del03.jsonnet
sites/hkg04.jsonnet
sites/lhr09.jsonnet
sites/ord07.jsonnet
sites/sin02.jsonnet
sites/syd07.jsonnet
sites/tpe02.jsonnet

These sites are in metros that already have a physical presence, so it should be safe to upgrade them to full probability without risking overwhelming the VM(s).
https://github.com/m-lab/ops-tracker/issues/1796
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/284)

Increases probability to 1 for many cloud sites

---

sites/arn01.jsonnet
sites/lis01.jsonnet
sites/lis02.jsonnet
sites/lis03.jsonnet

This change adds reduced site probabilities to all sites in the LIS metro. This change will collect measurements for client regions by directing them to a regional cloud companion metro in nearby MAD.
This change also corrects a typo in the retired arn01.jsonnet.
FYI: @laiyi-ohlsen this change is expected to go live next week.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/285)

Reduce LIS probability for MAD trial

---

sites/icn01.jsonnet
sites/kix01.jsonnet
sites/mel01.jsonnet

This change increases site probability for cloud sites icn, kix, and mel based on expected load.
Part of:
* https://github.com/m-lab/ops-tracker/issues/1796
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/286)

Use default probability for icn, kix, and mel cloud sites

---

retired.jsonnet
sites.jsonnet
sites/cgk01.jsonnet
sites/hel01.jsonnet
sites/icn01.jsonnet
sites/par06.jsonnet
sites/tpe02.jsonnet
sites/trn03.jsonnet
sites/waw01.jsonnet
sites/zrh01.jsonnet

IST will be rolling out in a number of new countries. This PR adds 2 additional VMs to countries where there are no physical machines deployed, and 1 additional VM in locations where M-Lab already has physical servers.
Additionally:
* retires site PAR06 (part of reduction of physical fleet)
* Sets probability for CGK01 to 1.0, now that there are 3 VMs there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/289)

Adds additional VMs in regions where IST will rollout

---

sites/dfw09.jsonnet

I suspect this got out of sync with GCP because I deployed these machines before I had implemented the local-exec TF provisioner to make sure that all ephemeral IPv6 addresses on machines get converted to static addresses and get assigned to the VM on update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/290)

Updates IPv6 addrs for mlab2/3-dfw09

---

sites/dfw09.jsonnet

Currently, the ndt-virtual configuration for the [staging mlab4-dfw09](https://github.com/m-lab/terraform-support/pull/23) MIG is not yet registered in siteinfo. As a result, the pods can start completely without uuid-annotator or heartbeat registration.
This change adds the IPv4 network configuration for the MIG frontend loadbalancer address. These MIGs are not yet enabled with IPv6 addresses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/291)

Add mlab4-dfw09 MIG IPv4 network configuration

---

sites/bom01.jsonnet

There has been a spike in traffic to bom01, which is a 1g site. 
This PR reduces the site's probability from 0.1 to 0.05.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/293)

Reduce the probability of bom01 to 0.05

---

sites/chs0t.jsonnet
sites/dfw09.jsonnet
sites/lax0t.jsonnet
sites/pdx0t.jsonnet

The Google Terraform provider now supports creating static IPv6 addresses for VMs and load balancers. This PR adds IPv6 addresses to the MIG load balancers in sandbox.
This PR also updates the IPv4 address of mlab3-dfw09, which was previously a standalone VM, but which is now a MIG. It does not yet have an IPv6 address because the changes to terraform-support enabling this are still in [a PR which is approved but which  I have not yet merged](https://github.com/m-lab/terraform-support/pull/41).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/296)

Adds IPv6 to sandbox MIGs + updates mlab3-dfw09 IPv4

---

sites/dfw09.jsonnet

We were experimenting with this name as a MIG in production. Now that we have switched it back to being a standalone VM, the IPs changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/298)

Updates IP information for mlab3-dfw09

---

sites/dfw09.jsonnet

In the previous PR, I had mistakenly entered an ephemeral IPv6 address. This sets it back to what it should be.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/299)

Fixes the IPv6 address for mlab3-dfw09

---

sites.jsonnet
sites/nuq0t.jsonnet

The ISC used to host a full M-Lab site, but could no longer do so. Instead they said they could host 1U with a /28. The old ISC site nuq02 was retired some time ago. This is completely a test/sandbox site for now. Rather than the typical machines+:{} definition, this new site uses a static machines definition with only a single mlab1 machine, as well as a /28 IPv4 prefix which will surely have unknown behavior and/or breakage. This is just a first start for testing in sandbox.
This was the result of the sandbox build, which seems okay so far:
```
$ host mlab1-nuq0t.mlab-sandbox.measurement-lab.org
mlab1-nuq0t.mlab-sandbox.measurement-lab.org has address 192.158.252.185
$ host mlab1d-nuq0t.mlab-sandbox.measurement-lab.org
mlab1d-nuq0t.mlab-sandbox.measurement-lab.org has address …
```

Adds new "select" test site nuq0t

---

retired.jsonnet
sites.jsonnet
sites/dfw10.jsonnet
sites/dfw11.jsonnet

Now that the periodic client causing all the problems in DFW is being blocked and the switch discard issues have gone away, we no longer need this extra virtual capacity in DFW.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/310)

Retires virtual sites DFW10 and DFW11

---

retired.jsonnet
sites.jsonnet
sites/gig03.jsonnet
sites/gig04.jsonnet

I _thought_ I had retired these sites months ago:
https://github.com/m-lab/siteinfo/commit/f4de5e6ab927510f2a9970aaeb163205c9c35819
However, I just discovered that they were not actually retired. Most likely I pushed these changes to my sandbox branch with the intention of creating a PR, but probably pushed some other changes to my sandbox branch before I ever created the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/314)

Retires sites GIG03 and GIG04

---

sites/dfw09.jsonnet

I was looking at logs for uuid-annotator in the ndt-virtual pod in mlab-staging on mlab4-dfw09 (a MIG) and was surprised to see error messages like `Can't annotate connection: Unknown direction` for the IPv6 address of the load balancer. I had expected the [recent update to uuid-annotator](https://github.com/m-lab/uuid-annotator/pull/63) to have resolved this, but then discovered that siteinfo didn't even have an IPv6 address configured for mlab4-dfw09. This PR should resolve that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/320)

Adds missing IPv6 address to mlab4-dfw09

---

experiments.jsonnet

Removing them breaks mlab-ns and the changes to accommodate this and make mlab-ns still work are too many, and involve even some bugs in GMX. It's too much work at the moment.
One practical effect this change has on supporting "minimal" sites with /28 and /29 IPv4 prefixes is that now /28 sites will only support up to index 10, and /29 sites will only support mask, ndt and ndt.iupui (without revtr). Both of these outcomes is probably just fine for v1 of minimal sites.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/321)

Adds back experiments ndt.iupui and mlab.neubot

---

formats/v2/sites/max-rates.json.jsonnet
lib/site.jsonnet

Previously, we assumed that if a site was 1g the max-rate should be one static thing, and that if it was 10g it should be another static thing. The introduction of "minimal" sites that only have a single server changes this.
Minimal sites should have the max-rate set higher than "full" sites. The max-rate values only apply to physical sites, since the number is [currently static for all virtual sites](https://github.com/m-lab/k8s-support/blob/main/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L67).
The results of the PR can be seen here:
https://siteinfo.mlab-sandbox.measurementlab.net/v2/sites/max-rates.json
Notably, site nuq0t has a max-rate of 7500000000, since nuq0t is the current ISC minimal pilot site.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

Adds a new function MaxRate() to the site object

---

formats/v2/zones/projects_measurement-lab.org.zone.jsonnet

This change adds new zone delegations for the sandbox and staging projects to the root measurement-lab-org zone.
These zones will be managed by the autojoin API with subzones for every registered organization. e.g. `mlab.sandbox.measurement-lab.org` or eventually `rnp.autojoin.measurement-lab.org`.
Before they can be effective, they must be deployed in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/325)

Add autojoin zone delegations

---

formats/v2/zones/measurement-lab.org.zone.jsonnet

This change completes the intention started in https://github.com/m-lab/siteinfo/pull/325 by adding the autojoin zone delegations to both measurement-lab.org zone files for the v1/v2 formats.
The v2 format now correctly includes these delegations: https://siteinfo.mlab-sandbox.measurementlab.net/v2/zones/measurement-lab.org.zone.diff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/326)

Add autojoin zone delegations to both zone header files

---

retired.jsonnet
sites.jsonnet
sites/nuq08.jsonnet

The test of the ISC "minimal" site with a single server and a /28 IPv4 prefix was successful in mlab-sandbox, and I believe we can now promote that machine to a new production site.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/322)

Promotes ISC machinefrom sandbox to production

---

sites/bom06.jsonnet
sites/cgk02.jsonnet
sites/chs02.jsonnet
sites/dfw12.jsonnet
sites/doh02.jsonnet
sites/gru06.jsonnet
sites/hel02.jsonnet
sites/icn02.jsonnet
sites/lax10.jsonnet
sites/waw02.jsonnet
sites/yul08.jsonnet
sites/zrh02.jsonnet

I'm trying this as a new strategy for deploying virtual sites. The old way was to create the resources in GCP using terraform-support, then note the static IPs created by GCP, then create the siteinfo records. The problem with this is that once the GCP resources are created, they join the cluster and start running workloads. Some of these workloads faile (namely uuid-annotator) because the site doesn't yet exist in siteinfo. This causes production alerts that cannot be managed with GMX, since GMX will not put anything into maintenance that doesn't exist in siteinfo.
The idea here is to create the site here in siteinfo, with an RFC1918 IPv4 address and no IPv6 address, and then push this through to production. Once this is in production, then an operator should place the sites into GMX …

Adds placeholder sites for new production MIGs

---

sites/bom06.jsonnet
sites/cgk02.jsonnet
sites/chs02.jsonnet
sites/dfw12.jsonnet
sites/doh02.jsonnet
sites/gru06.jsonnet
sites/hel02.jsonnet
sites/icn02.jsonnet
sites/lax10.jsonnet
sites/waw02.jsonnet
sites/yul08.jsonnet
sites/zrh02.jsonnet

Previously, the sites were added with placeholder addresses until the resources were actually created and we knew what the actual public IPs would be.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/329)

Adds real IPs for 2nd wave of MIGs in production

---

formats/v2/zones/measurement-lab.org.zone.jsonnet
formats/v2/zones/projects_measurement-lab.org.zone.jsonnet

This adds the autojoin zone delegations for `autojoin.measurement-lab.org` (https://github.com/m-lab/siteinfo/pull/326 and https://github.com/m-lab/siteinfo/pull/325 are previous PRs adding zone delegation for sandbox/staging).
See [here](https://console.cloud.google.com/net-services/dns/zones/autojoin-measurement-lab-org/details?project=mlab-autojoin) for the zone's configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/335)

Add zone delegation for autojoin.measurement-lab.org.

---

sites/ams10.jsonnet
sites/bom03.jsonnet
sites/bom05.jsonnet
sites/bom06.jsonnet
sites/bru06.jsonnet
sites/del05.jsonnet
sites/dfw09.jsonnet
sites/dfw12.jsonnet
sites/fra07.jsonnet
sites/gru05.jsonnet
sites/gru06.jsonnet
sites/hkg04.jsonnet
sites/hnd07.jsonnet
sites/iad09.jsonnet
sites/jnb02.jsonnet
sites/lax07.jsonnet
sites/lax10.jsonnet
sites/lhr10.jsonnet
sites/mad07.jsonnet
sites/mil08.jsonnet
sites/par08.jsonnet
sites/scl06.jsonnet
sites/sin02.jsonnet
sites/syd08.jsonnet
sites/tpe02.jsonnet
sites/trn03.jsonnet
sites/yul07.jsonnet
sites/yul08.jsonnet
sites/yyz07.jsonnet

The virtual sites affected by this PR are in metros where M-Lab currently has at least one or more physical sites. The idea is to push more clients to the physical site(s) in these metros, since those costs are fixed. Setting these sites to 50% probability should save quite a lot of GCP Internet egress traffic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/336)

Reduce probability to 50% for select virtual sites

---

sites/ams11.jsonnet
sites/ber02.jsonnet
sites/bru07.jsonnet
sites/cmh02.jsonnet
sites/fra08.jsonnet
sites/hkg05.jsonnet
sites/kix02.jsonnet
sites/las02.jsonnet
sites/mad08.jsonnet
sites/mel02.jsonnet
sites/mil09.jsonnet
sites/oma02.jsonnet
sites/par09.jsonnet
sites/pdx03.jsonnet
sites/sin03.jsonnet
sites/slc02.jsonnet
sites/tlv02.jsonnet
sites/tpe03.jsonnet
sites/trn04.jsonnet
sites/yyz08.jsonnet

https://docs.google.com/document/d/1fX_ndIN2M0MiaguxONTTSXqR2C-JnsSs4PFReY45HuQ/edit#heading=h.b31qf7vzme12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/339)

Adds round 3 MIGs for MIG migration

---

sites.jsonnet

This PR adds the `mel01` site back to the `sites` list. This site was deleted, seemingly by mistake, when the round 3 MIGs were added https://github.com/m-lab/siteinfo/pull/340/files. This is causing the pod to crash loop.
In the future, if the site does get removed, it will have to go under the `retired` list, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/341)

Add mel01 site back

---

retired.jsonnet
sites.jsonnet
sites/bom05.jsonnet

We already have MIG BOM06 in BOM, and don't need a 3-VM standalone site here. This got skipped over in the MIG migrations somehow because MIG BOM06 already existed, so I didn't try to migrate BOM05, but forgot to remove it anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/345)

Retires standalone VM site BOM05

---

sites/_default.jsonnet
sites/geg01.jsonnet
sites/pdx02.jsonnet
sites/sea10.jsonnet

The new Ziply "full" sites in Portland (PDX02), Seattle (SEA10) and Spokane (GEG01) are going to be using Juniper QFX5100-24Q switches, and will be on 40Gbps uplinks. This commit adds the suffix "-48s" to the default switch model for physical sites. The new Ziply sites will have a model of "qfx5100-24q". The switch-config repository will be configured with a new template for the 24Q model.
As far as I know, the only thing that currently uses the "model" field from switches.json is genconfig.py in the switch-config repository. @robertodauria, does this match your understanding? I want to be sure that this change doesn't break something else that consumes switches.json.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Changes default switch model to qfx5100-48s

---

lib/site.jsonnet

The new Ziply sites have 40Gbps uplinks. This sets the max-rates to 10Gbps for regular "full" sites, and 30Gbps for "minimal" sites.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/349)

Add txcontroller max-rate rules for 40Gbps uplinks

---

formats/v2/retired/placeholder.json.jsonnet
formats/v2/retired/sites.json.jsonnet

I had a need to collect information about retired sites. Specifically, how many physical sites were retired for a given set of years.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/352)

Produces sites.json, but for retired sites in v2 format

---

retired.jsonnet
sites.jsonnet
sites/lju01.jsonnet

The site has always been limited to 100Mbps, and this just isn't workable in 2025.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/358)

Retires site LJU01

---

sites/cmh02.jsonnet
sites/kix02.jsonnet

Mostly spill Osaka (kix)  to Tokyo (hnd) and Seoul (icn). 
Mostly spill Columbus (cmh) to Chicago (ord), Washington (iad) and Toronto (yyz).
The alternate sites are all include substantial flatrate serving (non-GCS) sites.
Seoul also has relatively expensive GCS egress, however it already carries the the majority of Korean traffic.  Japan traffic is expected to spill to Tokyo, which is mostly physical.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/361)

Spill 75% of Osaka (kix) and Columbus (cmh) to less expensive sites
