cloudbuild.yaml
This change completes https://github.com/m-lab/siteinfo/pull/10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/11)
=> Set PROJECT in environment

sites/mia04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/19)
=> Updates MIA04 to 10g.

sites/lca01.jsonnet, sites/mpm01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/20)
=> Sets machine count to 3 for a couple sites that have not been upgraded.

sites/del01.jsonnet, sites/maa01.jsonnet
This PR adds the DEL01 (New Delhi) and MAA01 (Chennai) sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/23)
=> Add DEL01 and MAA01 sites

sites/hnd03.jsonnet
This PR adds [hnd03](https://github.com/m-lab/ops-tracker/issues/755) to siteinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/25)
=> Create new site hnd03

Dockerfile
This PR adds curl (required by `zonediff.sh`) to the jsonnet-env image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/26)
=> Add curl to the docker image

sites/del01.jsonnet, sites/maa01.jsonnet
This PR updates the coordinates for sites maa01 and del01.
These were previously set to the city's coordinates, rather than the airport's coordinates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/30)
=> Update coordinates for maa01 and del01

sites.jsonnet, sites/gru01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/35)
=> Adds new site GRU01 (Sao Paulo).

sites.jsonnet, sites/gru02.jsonnet
This PR adds details for the [new site](https://github.com/m-lab/ops-tracker/issues/797) GRU02.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/37)
=> Add new site GRU02

cmd/mlabconfig.py
This is the first step in resolving issue https://github.com/m-lab/epoxy-images/issues/136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/41)
=> Adds uplink_speed to the template output for the function export_mlab_server_network_config()

cmd/mlabconfig.py
Reverts m-lab/siteinfo#41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/42)
=> Revert "Adds uplink_speed to the template output for the function export_mlab_server_network_config()"

sites.jsonnet, sites/yqm01.jsonnet, sites/yqm02.jsonnet
YQM01 is being replaced by YQM02, which will have a 10g circuit provided by F6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/43)
=> Adds new site YQM02, and fixes site YQM01

sites.jsonnet, sites/gru04.jsonnet
This PR adds the [new site GRU04](https://github.com/m-lab/ops-tracker/issues/828) to siteinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/45)
=> Add new site GRU04

sites.jsonnet, sites/gru03.jsonnet
This PR adds the new site GRU03 to siteinfo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/46)
=> Add new site GRU03

sites.jsonnet, sites/vie02.jsonnet
The IPv6 prefix for VIE01 is changing, necessitating a change in site name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/55)
=> Adds new site VIE02, which will be replacing site VIE01

sites.jsonnet, sites/hkg01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/60)
=> Adds new site HKG01.

formats/sites/switches.json.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/62)
=> Adds rstp field to the switches format.

sites/dfw03.jsonnet, sites/ord06.jsonnet
The actual upgrade will happen sometimes next week, but the new configuration on switch port xe-0/0/45 has been applied already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/66)
=> Update DFW03 and ORD06 to 10g

formats/adhoc/upgrade-2nd.json.jsonnet, formats/adhoc/upgrade-3rd.json.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/73)
=> Adds site DEL02 to the list of already migrated sites.

sites.jsonnet, sites/lhr06.jsonnet, sites/lhr07.jsonnet
This PR adds two new sites to siteinfo:
- LHR06: https://github.com/m-lab/ops-tracker/issues/927
- LHR07: https://github.com/m-lab/ops-tracker/issues/928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/79)
=> Add LHR06 and LHR07

sites/dfw03.jsonnet, sites/lax04.jsonnet, sites/ord06.jsonnet
ORD06, DFW03 and LAX04 were just cut-over to 10g circuits a few minutes ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/81)
=> Updates transit and switch information for three Level3 circuits

sites/atl08.jsonnet, sites/den02.jsonnet, sites/lga05.jsonnet, sites/mia06.jsonnet, sites/sea04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/82)
=> Updates switch information for 5 more Level3 circuits that were upgraded to 10g

sites/iad05.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/88)
=> Updates site iad05 from 1g to 10g.

experiments.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/94)
=> Removes experiments that are no longer on the platform

Makefile, README.md, cloudbuild.yaml, formats/sites/geo.json.jsonnet, formats/sites/sites.json.jsonnet, index.html.jsonnet
This change adds the generation of an index.html file for all output files.
This should make discovering files and sharing links easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/95)
=> Add index for generated siteinfo files

cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/101)
=> Adds the new switch-config build trigger to the cloudbuild config file.

sites/lhr05.jsonnet, sites/mil04.jsonnet
These two sites have been upgraded. I've removed the configuration for port ge-0/0/47 already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/104)
=> Upgrade lhr05 and mil04 to 10g

sites/hkg02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/105)
=> Fixes an incorrect IPv4 prefix for HKG02.

sites.jsonnet, sites/mad05.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/106)
=> Adds new site MAD05 with a 10g Tata circuit.

experiments.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/109)
=> Removes SK experiment from experiments.json.

sites.jsonnet, sites/lis03.jsonnet
Ticket: https://github.com/m-lab/ops-tracker/issues/1031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/114)
=> Add new site LIS03 (TATA, 10GB)

sites.jsonnet, sites/gig01.jsonnet
Ticket: https://github.com/m-lab/ops-tracker/issues/990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/115)
=> Add new site GIG01 (Telxius, 10GB)

sites.jsonnet, sites/bog02.jsonnet
Ticket: https://github.com/m-lab/ops-tracker/issues/989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/116)
=> Add new site BOG02 (Telxius, 10G)

formats/v2/sites/hostnames.json.jsonnet, formats/v2/sites/placeholder.json.jsonnet, formats/v2/sites/sites.json.jsonnet
This is accomplished by symlinking to the corresponding v1 jsonnet files. I've only made symlinks for these two file, since there would otherwise be no change in the output for any of the other files between v1 and v2. That said, if we want the v2 "api" to contain everything that the v1 "api" contains, then it will be simple enough to symlink all the other files too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/123)
=> Adds v2 generation for sites.json and hostnames.json

sites/hnd04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/124)
=> Updates IP prefixes and ASN for HND04. GTT changed them.

sites.jsonnet, sites/mrs03.jsonnet
This issue is a start to resolving m-lab/ops-tracker/issues/1037.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/126)
=> Adds new site CenturyLink (Level3) site MRS03.

sites/lga0t.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/129)
=> Fixes lga0t typos, putting mlab3 and mlab4 in mlab-sandbox project.

experiments.jsonnet
In support of https://github.com/m-lab/k8s-support/pull/400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/136)
=> Add revtr to experiments

Dockerfile.python, cloudbuild.yaml, cmd/mlabconfig.py, cmd/mlabconfig_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/138)
=> Changes made by 2to3 to make mlabconfig.py compatible with python3.

cmd/mlabconfig.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/139)
=> Make mlabconfig.py use python3 by default.

sites.jsonnet, sites/mex01.jsonnet, sites/mty01.jsonnet
The circuits will be from Transtelco.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/144)
=> Adds new sites MEX01 and MTY01

sites.jsonnet, sites/los02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/146)
=> Adds new 10g site LOS02 with MTN.

sites.jsonnet, sites/mnl02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/148)
=> Adds new 10g site MNL02 through RISE.

sites.jsonnet, sites/gig03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/157)
=> Adds new Internexa site GIG03.

sites.jsonnet, sites/gig04.jsonnet, sites/mex02.jsonnet, sites/yyz03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/158)
=> Adds new sites GIG04 (CTL), MEX02 (CTL) and YYZ03 (GTT).

sites/mrs03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/160)
=> Adds IPv6 prefix for TI site MRS03.

sites/mrs01.jsonnet, sites/mrs02.jsonnet, sites/mrs03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/161)
=> Set model: r640 on some of the new sites

sites/ams09.jsonnet, sites/mil06.jsonnet, sites/par06.jsonnet
These IPv6 updates were provided by Mike in their respective ops-tracker issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/162)
=> Adds or updates IPv6 prefixes for a few TI sites.

sites.jsonnet, sites/par07.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/163)
=> Adds new TATA site PAR07

sites.jsonnet, sites/mrs04.jsonnet
This PR adds the new site MRS04. Corresponding ops-tracker issue is here: https://github.com/m-lab/ops-tracker/issues/1223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/164)
=> Add new site MRS04 (TATA)

sites.jsonnet, sites/fra06.jsonnet
https://github.com/m-lab/ops-tracker/issues/1238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/165)
=> Add new site FRA06 (TI Sparkle)

sites.jsonnet, sites/mil07.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/166)
=> Adds new TATA site MIL07.

sites/gig02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/169)
=> Adds IPv6 prefix for GIG02.

sites/bog02.jsonnet, sites/bog03.jsonnet, sites/bog04.jsonnet, sites/bog05.jsonnet, sites/mrs04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/170)
=> Update model on R640 sites.

sites.jsonnet, sites/yyz04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/171)
=> Add new site YYZ04 (TATA)

sites/yyz04.jsonnet
https://github.com/m-lab/ops-tracker/issues/1279#issuecomment-756848146
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/172)
=> Update yyz04.jsonnet with the correct IPv4 subnet

sites.jsonnet, sites/mex03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/176)
=> Adds new GTT site MEX03

sites.jsonnet, sites/yul03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/177)
=> Adds new GTT site YUL03

sites.jsonnet, sites/yul05.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/178)
=> Adds new Telia site YUL05

sites.jsonnet, sites/yul04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/179)
=> Adds new TATA site YUL04

sites/tnr01.jsonnet
The site host upgraded the uplink to 10g.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/183)
=> Upgrades TNR01 to a 10g uplink

sites.jsonnet, sites/yvr02.jsonnet, sites/yyz05.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/193)
=> Adds new Telia sites yvr02 and yyz05

sites.jsonnet, sites/yvr04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/195)
=> Add new site YVR04 (GTT)

sites.jsonnet, sites/hnl01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/198)
=> Adds new GTT site HNL01

sites.jsonnet, sites/eze02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/200)
=> Adds new TI site EZE02

cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/201)
=> Increases build timeout to 15m

sites.jsonnet, sites/eze04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/204)
=> Adds new Internexa site EZE04

sites/lim04.jsonnet
Update to IPv4 assignment in https://github.com/m-lab/ops-tracker/issues/1463 for lim04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/212)
=> Update lim04 IPv4 assignment

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/213)
=> Updates README with info useful to dev/API users

sites.jsonnet, sites/syd04.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/216)
=> Adds new GTT site SYD04

sites.jsonnet, sites/per02.jsonnet
#217 was accidentally closed. This PR replaces it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/218)
=> Adds new Superloop site PER02

sites.jsonnet, sites/per01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/223)
=> Adds new Vocus site PER01

formats/v2/sites/machines.json.jsonnet, formats/v2/sites/max-rates.json.jsonnet, formats/v2/zones/measurement-lab.org.zone.jsonnet, formats/v2/zones/projects_measurement-lab.org.zone.jsonnet, index.html.jsonnet, sites/cgk01.jsonnet, sites/chs0t.jsonnet, sites/eze01.jsonnet, sites/eze02.jsonnet, sites/eze03.jsonnet, sites/eze04.jsonnet, sites/iad07.jsonnet, sites/lim01.jsonnet, sites/lim02.jsonnet, sites/lim03.jsonnet, sites/los02.jsonnet, sites/pdx0t.jsonnet, sites/scl01.jsonnet, sites/scl02.jsonnet, sites/scl03.jsonnet, sites/scl04.jsonnet, sites/tpe02.jsonnet
To produce this commit I used the "Format Files" vscode extension,
globbing on all files with a "jsonnet" extension.
This PR contains no functional changes, and is just formatting.
Interestingly, the vscode jsonnet formatter doesn't appear to like newlines at the end of a file. It has been my impression that a newline at the end of the file was generally good practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/227)
=> Formats files using vscode jsonnet formatter

sites.jsonnet, sites/syd05.jsonnet, sites/syd06.jsonnet
This adds the two new sites SYD05 (Vocus) and SYD06 (Superloop)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/231)
=> Add SYD05 and SYD06

sites.jsonnet, sites/lax08.jsonnet
This new virtual site brings us a dual stack (IPv4/IPv6) site to staging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/232)
=> Adds new virtual site lax08

sites.jsonnet, sites/sof01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/234)
=> Adds new GTT site SOF01

sites.jsonnet, sites/sof02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/237)
=> Adds new Telia site SOF02

formats/v2/sites/registration.json.jsonnet
Link: https://siteinfo.mlab-sandbox.measurementlab.net/v2/sites/registration.json.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/240)
=> Add mapping of FQDN to registration

sites.jsonnet, sites/mpm02.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/242)
=> Adds new Vodacom site MPM02

sites.jsonnet, sites/oma01.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/243)
=> Adds new virtual site OMA01

sites/bom03.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/248)
=> Adds an mlab2 VM to virtual site bom03

sites.jsonnet, sites/yqm02.jsonnet, sites/ywg02.jsonnet, sites/yyc03.jsonnet
https://github.com/m-lab/ops-tracker/issues/1668
https://github.com/m-lab/ops-tracker/issues/1667
https://github.com/m-lab/ops-tracker/issues/1666
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/250)
=> Adds new HE sites YQM02, YWG02, YYC03

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/253)
=> Add ./sites/registration.json to README

experiments.jsonnet
This changes the temporary "demo1" experiment name to "msak" so that the correct subdomains are generated at build time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/256)
=> Rename experiment with index 1 from demo1 to msak

sites/bom01.jsonnet, sites/bom02.jsonnet, sites/bom03.jsonnet, sites/del01.jsonnet, sites/del03.jsonnet, sites/maa01.jsonnet, sites/maa02.jsonnet
This change updates the lat/lon of sites in India to share a common center position within the country. This is a manual approach to conducting a "spray" experiment from clients within India to all locations within the country. This will help use see the performance impacts from different geographic regions within the country to all other M-Lab locations within India. This performance assessment will help decide whether physical pods are needed companions to the cloud locations or if alternate physical locations are sufficient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/262)
=> Position all Indian sites at center of India

retired.jsonnet, sites.jsonnet, sites/yul02.jsonnet
https://github.com/m-lab/ops-tracker/issues/1735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/264)
=> Retires legacy CIRA 1g HE site YUL02

sites/chs0t.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/267)
=> Fixes IP addresses for mlab2-chs0t

retired.jsonnet, sites.jsonnet, sites/gru04.jsonnet
This is part of the process of retiring ~1/3 of the physical fleet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/271)
=> Retires site GRU04

sites/dfw09.jsonnet
This is to add extra capacity in DFW to help alleviate switch discards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/274)
=> Adds 2 new VMs to virtual site dfw09

sites.jsonnet, sites/atl0t.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/276)
=> Add atl0t for testing

sites.jsonnet, sites/lax09.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/277)
=> Adds new virtual site lax09 with Equinix

sites/bom01.jsonnet, sites/bom02.jsonnet, sites/bom03.jsonnet, sites/del01.jsonnet, sites/del03.jsonnet, sites/maa01.jsonnet, sites/maa02.jsonnet
This reverts commit 5dcecaa4178011f4d7c78a44cf3e036fefb36d0d.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/278)
=> Revert "Position all Indian sites at center of India (#262)"

cloudbuild.yaml
See comment in change set for rationale.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/283)
=> Trigger builds of prometheus-support, too

sites/lis01.jsonnet, sites/lis02.jsonnet, sites/lis03.jsonnet
This change reverts the probability changes from https://github.com/m-lab/siteinfo/pull/285 The collection trial period will end Aug 2nd, and the deployment of these changes will take up to 24hrs to complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/287)
=> Revert LIS->MAD trial

retired.jsonnet, sites.jsonnet, sites/atl0t.jsonnet, sites/lax09.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/288)
=> Retire trial Equinix sites

retired.jsonnet, sites.jsonnet, sites/scl04.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1730300611
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/297)
=> Retires Internexa site SCL04

retired.jsonnet, sites.jsonnet, sites/lga09.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1755995148
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/301)
=> Retires site LGA09

retired.jsonnet, sites.jsonnet, sites/par02.jsonnet
https://github.com/m-lab/ops-tracker/issues/1862
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/303)
=> Retires Lumen site PAR02

retired.jsonnet, sites.jsonnet, sites/dfw07.jsonnet, sites/fra01.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1804702654
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1804711792
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/304)
=> Retires Telia sites DFW07 and FRA01

sites.jsonnet, sites/dfw11.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/307)
=> Adds new virtual site DFW11

retired.jsonnet, sites.jsonnet, sites/atl03.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1861129537
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/311)
=> Retires site ATL03

retired.jsonnet, sites.jsonnet, sites/iad06.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1861384945
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/312)
=> Retires site IAD06

retired.jsonnet, sites.jsonnet, sites/ams08.jsonnet, sites/atl07.jsonnet
https://github.com/m-lab/ops-tracker/issues/1716
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/313)
=> Retires sites AMS08 and ATL07

retired.jsonnet, sites.jsonnet, sites/fra06.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-1921774312
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/317)
=> Retires site FRA06

sites/iad08.jsonnet
I mistakenly deleted the addresses from GCP, and the new static addresses that were created are different.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/323)
=> Fixes IP addresses for mlab4-iad08

retired.jsonnet, sites.jsonnet, sites/hkg01.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-2025776722
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/330)
=> Retires site HKG01

experiments.jsonnet
This PR adds "pt" to the list of siteinfo experiments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/334)
=> Add "pt" experiment

sites.jsonnet, sites/dfw13.jsonnet
This is being added so that we have at least 1 MIG in staging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/342)
=> Add virtual MIG site dfw13

retired.jsonnet, sites.jsonnet, sites/eze03.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-2259464793
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/343)
=> Retires Telefonica site EZE03

retired.jsonnet, sites.jsonnet, sites/bog04.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-2361392005
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/347)
=> Retires site BOG04

retired.jsonnet, sites.jsonnet, sites/hnd05.jsonnet
https://github.com/m-lab/ops-tracker/issues/1743#issuecomment-2455224355
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/353)
=> Retires site HND05

cloudbuild.yaml
Container Registry is being retired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/359)
=> Updates Cloud Build to use Artifact Registry container images

experiments.jsonnet
We have not communicated with them in a very long time, we are not sure whether they are even using it still.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/362)
=> Removes flooefi as an experiment

experiments.jsonnet
This reverts commit 12386656381bacb6eafccba4c63118b780628476.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/siteinfo/363)
=> Revert "Removes flooefi as an experiment (#362)"
